import { ModelDefinition } from "@/types/a2i.types";

export const models: ModelDefinition[] = [
  {
    id: "black-forest-labs/flux-dev",
    name: "FLUX-dev",
    description: "High-quality image generation with advanced controls",
    schema: {
      title: "FLUX-dev Input",
      required: ["prompt"],
      properties: {
        // prompt: {
        //   type: "string",
        //   title: "Prompt",
        //   displayTitle: "What do you want to create?",
        //   description:
        //     "Describe your vision in detail. Be specific about style, mood, colors, and composition.",
        //   "x-priority": 1,
        //   "x-group": "essentials",
        // },
        aspect_ratio: {
          type: "enum",
          enum: [
            "1:1",
            "16:9",
            "21:9",
            "3:2",
            "2:3",
            "4:5",
            "5:4",
            "3:4",
            "4:3",
            "9:16",
            "9:21",
          ],
          title: "Aspect Ratio",
          displayTitle: "Image Shape",
          description: "Choose the proportions of your generated image",
          default: "1:1",
          "x-priority": 2,
          "x-group": "essentials",
        },
        // image_input: {
        //   type: "file",
        //   title: "Reference Image",
        //   displayTitle: "Reference Image (Optional)",
        //   description:
        //     "Upload an image to use as reference for style or composition",
        //   "x-priority": 5,
        //   "x-group": "essentials",
        // },
        prompt_strength: {
          type: "number",
          title: "Prompt Strength",
          displayTitle: "How much to follow the reference image",
          description:
            "Higher values follow the reference image more closely. Lower values give more creative freedom.",
          default: 0.8,
          maximum: 1,
          minimum: 0,
          "x-priority": 11,
          "x-group": "generation",
        },
        num_outputs: {
          type: "integer",
          title: "Number of Images",
          displayTitle: "How many images to generate",
          description: "Generate multiple variations to choose from",
          default: 1,
          maximum: 4,
          minimum: 1,
          "x-priority": 12,
          "x-group": "generation",
        },
        num_inference_steps: {
          type: "integer",
          title: "Quality Steps",
          displayTitle: "Generation quality (more steps = better quality)",
          description:
            "More steps produce higher quality but take longer. 28-35 is usually optimal.",
          default: 28,
          maximum: 50,
          minimum: 1,
          "x-priority": 13,
          "x-group": "generation",
        },
        guidance: {
          type: "number",
          title: "Guidance Scale",
          displayTitle: "How closely to follow your prompt",
          description:
            "Higher values follow your prompt more strictly. Try 2-4 for more natural results.",
          default: 3,
          maximum: 10,
          minimum: 0,
          "x-priority": 14,
          "x-group": "generation",
        },
        output_format: {
          type: "enum",
          enum: ["webp", "jpg", "png"],
          title: "File Format",
          displayTitle: "Image file format",
          description:
            "WebP offers best compression, PNG for transparency, JPG for compatibility",
          default: "webp",
          "x-priority": 21,
          "x-group": "output",
        },
        output_quality: {
          type: "integer",
          title: "Image Quality",
          displayTitle: "Image compression quality",
          description:
            "Higher values produce larger files with better quality. Not used for PNG.",
          default: 80,
          maximum: 100,
          minimum: 0,
          "x-priority": 22,
          "x-group": "output",
        },
        megapixels: {
          type: "enum",
          enum: ["1", "0.25"],
          title: "Resolution",
          displayTitle: "Image resolution",
          description:
            "Higher resolution for more detail, but takes longer to generate",
          default: "1",
          "x-priority": 23,
          "x-group": "output",
        },
        go_fast: {
          type: "boolean",
          title: "Fast Mode",
          displayTitle: "Fast generation mode",
          description:
            "Enable optimizations for faster generation with slightly reduced quality",
          default: true,
          "x-priority": 31,
          "x-group": "advanced",
        },
        seed: {
          type: "integer",
          title: "Seed",
          displayTitle: "Reproducibility seed",
          description:
            "Set a specific number to get the same result every time. Leave empty for random results.",
          "x-priority": 32,
          "x-group": "advanced",
        },
        disable_safety_checker: {
          type: "boolean",
          title: "Skip Safety Checks",
          displayTitle: "Skip content safety checks",
          description: "Disable automatic content filtering (use responsibly)",
          default: false,
          "x-priority": 33,
          "x-group": "advanced",
        },
      },
    },
  },
  {
    id: "black-forest-labs/flux-1.1-pro",
    name: "FLUX-1.1-pro",
    description: "Professional grade image generation with enhanced controls",
    schema: {
      title: "FLUX-1.1-pro Input",
      required: ["prompt"],
      properties: {
        // prompt: {
        //   type: "string",
        //   title: "Prompt",
        //   displayTitle: "What do you want to create?",
        //   description:
        //     "Describe your vision in detail. Be specific about style, mood, colors, and composition.",
        //   "x-priority": 1,
        //   "x-group": "essentials",
        // },
        aspect_ratio: {
          type: "enum",
          enum: [
            "custom",
            "1:1",
            "16:9",
            "3:2",
            "2:3",
            "4:5",
            "5:4",
            "9:16",
            "3:4",
            "4:3",
          ],
          title: "Aspect Ratio",
          displayTitle: "Image Shape",
          description:
            "Choose the proportions of your generated image, or select 'custom' for specific dimensions",
          default: "1:1",
          "x-priority": 2,
          "x-group": "essentials",
        },
        width: {
          type: "integer",
          title: "Width",
          displayTitle: "Custom Width",
          description:
            "Width in pixels (only used when aspect ratio is 'custom'). Will be rounded to nearest multiple of 32.",
          maximum: 1440,
          minimum: 256,
          "x-priority": 3,
          "x-group": "essentials",
        },
        height: {
          type: "integer",
          title: "Height",
          displayTitle: "Custom Height",
          description:
            "Height in pixels (only used when aspect ratio is 'custom'). Will be rounded to nearest multiple of 32.",
          maximum: 1440,
          minimum: 256,
          "x-priority": 4,
          "x-group": "essentials",
        },
        // image_input: {
        //   type: "file",
        //   title: "Reference Image",
        //   displayTitle: "Reference Image (Optional)",
        //   description:
        //     "Upload an image to use as reference for style or composition",
        //   "x-priority": 5,
        //   "x-group": "essentials",
        // },
        output_format: {
          type: "enum",
          enum: ["webp", "jpg", "png"],
          title: "File Format",
          displayTitle: "Image file format",
          description:
            "WebP offers best compression, PNG for transparency, JPG for compatibility",
          default: "webp",
          "x-priority": 21,
          "x-group": "output",
        },
        output_quality: {
          type: "integer",
          title: "Image Quality",
          displayTitle: "Image compression quality",
          description:
            "Higher values produce larger files with better quality. Not used for PNG.",
          default: 80,
          maximum: 100,
          minimum: 0,
          "x-priority": 22,
          "x-group": "output",
        },
        safety_tolerance: {
          type: "integer",
          title: "Safety Tolerance",
          displayTitle: "Content safety level",
          description:
            "1 is most strict, 6 is most permissive. Controls how strict content filtering is.",
          default: 2,
          maximum: 6,
          minimum: 1,
          "x-priority": 34,
          "x-group": "advanced",
        },
        prompt_upsampling: {
          type: "boolean",
          title: "Prompt Enhancement",
          displayTitle: "Enhance prompt automatically",
          description:
            "Automatically improve your prompt for more creative and detailed generation",
          default: false,
          "x-priority": 35,
          "x-group": "advanced",
        },
        seed: {
          type: "integer",
          title: "Seed",
          displayTitle: "Reproducibility seed",
          description:
            "Set a specific number to get the same result every time. Leave empty for random results.",
          "x-priority": 32,
          "x-group": "advanced",
        },
      },
    },
  },

  {
    id: "gpt-image-1",
    name: "GPT-Image-1",
    description:
      "Advanced multimodal image generation with transparency, quality, and moderation controls.",
    schema: {
      title: "GPT-Image-1 Input",
      required: ["prompt"],
      properties: {
        // prompt: {
        //   type: "string",
        //   title: "Prompt",
        //   description: "Text prompt describing the desired image",
        //   "x-order": 1,
        // },
        background: {
          type: "enum",
          enum: ["auto", "transparent", "opaque"],
          title: "Background",
          default: "auto",
          description: "Background transparency setting",
          "x-order": 2,
        },
        moderation: {
          type: "enum",
          enum: ["auto", "low"],
          title: "Moderation Level",
          default: "auto",
          description: "Content moderation strictness",
          "x-order": 4,
        },
        n: {
          type: "integer",
          title: "Number of Images",
          minimum: 1,
          maximum: 10,
          default: 1,
          description: "Number of images to generate",
          "x-order": 5,
        },
        output_compression: {
          type: "integer",
          title: "Output Compression",
          minimum: 0,
          maximum: 100,
          default: 100,
          description: "Compression level for output images (for webp/jpeg)",
          "x-order": 6,
        },
        output_format: {
          type: "enum",
          enum: ["png", "jpeg", "webp"],
          title: "Output Format",
          default: "png",
          description: "Format of the output images",
          "x-order": 7,
        },
        quality: {
          type: "enum",
          enum: ["high", "medium", "low"],
          title: "Quality",
          default: "high",
          description: "Image quality level",
          "x-order": 8,
        },
        size: {
          type: "enum",
          enum: ["1024x1024", "1536x1024", "1024x1536"],
          title: "Size",
          default: "1024x1024",
          description: "Size of the generated image",
          "x-order": 10,
        },
      },
    },
  },
];
