FROM node:18-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
RUN npm install --only=production
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1


# ARGs
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_API_BASE_URL_PROD
ARG NEXT_PUBLIC_API_BASE_URL_STG
ARG NEXT_PUBLIC_API_BASE_URL_DEV
ARG FIREBASE_ADMIN_CLIENT_EMAIL
ARG FIREBASE_ADMIN_PRIVATE_KEY
ARG AUTH_COOKIE_NAME
ARG AUTH_COOKIE_SIGNATURE_KEY_CURRENT
ARG AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS
ARG USE_SECURE_COOKIES
ARG NEXT_PUBLIC_ENVIRONMENT

# ENVIRONMENT VARIABLES
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_API_BASE_URL_PROD=$NEXT_PUBLIC_API_BASE_URL_PROD
ENV NEXT_PUBLIC_API_BASE_URL_STG=$NEXT_PUBLIC_API_BASE_URL_STG
ENV NEXT_PUBLIC_API_BASE_URL_DEV=$NEXT_PUBLIC_API_BASE_URL_DEV
ENV FIREBASE_ADMIN_CLIENT_EMAIL=$FIREBASE_ADMIN_CLIENT_EMAIL
ENV FIREBASE_ADMIN_PRIVATE_KEY=$FIREBASE_ADMIN_PRIVATE_KEY
ENV AUTH_COOKIE_NAME=$AUTH_COOKIE_NAME
ENV AUTH_COOKIE_SIGNATURE_KEY_CURRENT=$AUTH_COOKIE_SIGNATURE_KEY_CURRENT
ENV AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS=$AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS
ENV USE_SECURE_COOKIES=$USE_SECURE_COOKIES
ENV NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./
USER nextjs

EXPOSE 3000

ENV PORT=3000

CMD ["npm", "start"]